name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Simulate Deployment
      run: echo "✅ Deployment approved and would happen here if this was a real environment."